### ISSUE TITLE
upgrade to level-sublevel 6

### ISSUE THREAD

**Issue by pgte** [pgte/level-jobs#10]

**Comment by mshick** [comment]
Looks like you've got support in. I'll drop my PR and fork. Thanks!

**Comment by mshick** [comment]
FYI, the version currently on NPM seems to be broken. It doesn't have your recent changes. I think you may have published two version 0.5.0s and it has kept the original. If you bump to 0.5.1 it should pick up the changes.

**Comment by pgte** [comment]
Good call, thanks.

Published v0.5.1, please check.
