### ISSUE TITLE
Add a retry event?

### ISSUE THREAD

**Issue by juice49** [pgte/level-jobs#13]
Hey Pedro, thanks for the awesome library, it has proven very useful to me!

I have just found myself in a scenario in which I'd like to execute a function upon a worker retry.

I at first tried listening for the error event on the queue instance, but after looking at the source can see that an [error is only emitted when the max retries are reached](https://github.com/pgte/level-jobs/blob/838390ca7d12180ecf6fa4730f91ff0e45fd9cae/server.js#L157).

Would you be receptive to a PR that adds a retry event that is emitted for each retry?

**Comment by pgte** [comment]
@juice49 I never needed it but I'd welcome a PR with this feature. :)

**Comment by juice49** [comment]
Great, thanks. Currently putting this together (:
