### ISSUE TITLE
query already finished job

### ISSUE THREAD

**Issue by myf** [pgte/level-jobs#16]
since the examples indicate that you can only query pending jobs not the entire historical jobs, I wonder if there's a way to see if the new job has an unique ID that was not processed by any historical job?

**Comment by pgte** [comment]
@myf I'm not sure I understood your question.

The jobId is locally unique and is created by this function: https://github.com/pgte/level-jobs/blob/master/timestamp.js

**Comment by myf** [comment]
@pgte sorry that i didn't make it clear, my original question was like this:

I have a task i want to finish, let's say there's a few thousand jobs in the queue, but some of them are the same as others. I want to be able to work the queue and also check if certain job has been executed already.

I took a closer look at the implementation and the content in leveldb it seems that only pending tasks and unexcuted tasks are stored in. whatever is excuted will be removed from the queue. I guess that makes sense and sorry i think i asked a wrong question and didn't ask clearly.
