### ISSUE TITLE
Unable to get it working with node v 6.9 LTS

### ISSUE THREAD

**Issue by manishbhatias** [pgte/level-jobs#19]

**Comment by pgte** [comment]
@manishbhatias could you please elaborate?
All tests seam to run ok on node v6.9...

**Comment by manishbhatias** [comment]
@pgte 

When I try to install level-jobs and run my code. It crashes with an error that it was not able to find leveldown.

    "LevelUPError: Could not locate LevelDOWN, try `npm install leveldown`"

When I try to install the leveldown package using npm, and run my code again it gives another error

    "LevelUPError: Installed version of LevelDOWN (1.5.0) does not match required version (~0.10.0)"

**Comment by pgte** [comment]
level-jobs does not depend on level or level down. those are dependencies of your application.
Looks like you probably have a dependency mismatch in your installation?
Perhaps try installing the `level` package locally to the app (bundles levelup and leveldown).

**Comment by manishbhatias** [comment]
@pgte 

I think level-jobs depends on level-sublevel which in turn depends on levelup.

I tried solving version mismatch by installing a lower version of leveldown but it does not build with node v 6.9

**Comment by manishbhatias** [comment]
@pgte 

It seems that there is an issue with package resolution in yarn package manager. I tried installing the dependencies using npm and it seems to work now.

I'll check the difference in installed package versions with yarn and npm and open an issue with the yarn package manager.

Thanks for your help.
