### ISSUE TITLE
ability to get running jobs

### ISSUE THREAD

**Issue by derhuerst** [pgte/level-jobs#22]
It seems that, right now, `client.readStream()` only gives you *queued* tasks, but not *running* (aka `pending`) jobs. It would be nice to have this feature.

**Comment by derhuerst** [comment]
I can see that the `pending` sublevel is held by `server.js`, whereas `work` is held by `client.js` and it makes sense to conceptually keep them separate. I might make sense to initiate the `pending` sublevel in `client.js` as well.

**Comment by pgte** [comment]
This makes sense, but I think it would be required to get separate read streams; one for queued and one for running. The API could be something like: `client.pending.readStream()` and `client.running.readStream()`.
@derhuerst what do you say?

**Comment by derhuerst** [comment]
looks good! what i don't like is that the `client.pending` and `client.running` sublevel instances "invite" you to write to them. while it's technically always possible to disturb a lib running on top of LevelDB, it might be confusing to have a "hey, here's a writable DB instance, have fun with it!" setup. does that make sense? 😛

**Comment by pgte** [comment]
agree, I don't think you should expose the sublevel directly, but, for each, only provide a single object with that particular `.readStream()` method. Makes sense?

**Comment by derhuerst** [comment]
What do you think about `.runningStream()` and `.pendingStream()`?

**Comment by pgte** [comment]
@derhuerst ok with me.

**Comment by pgte** [comment]
Fixed by https://github.com/pgte/level-jobs/pull/23, landed on v2.0.0
